CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating INTEGER NOT NULL,
    comment VARCHAR(500),
    accommodation_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_accommodation
        FOREIGN KEY (accommodation_id) REFERENCES accommodation(id)
);

CREATE TABLE activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    message VARCHAR(500) NOT NULL,
    accommodation_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_log_accommodation
        FOREIGN KEY (accommodation_id) REFERENCES accommodation(id)
);

CREATE TABLE accommodation_aggregate (
    accommodation_id BIGINT PRIMARY KEY,
    accommodation_name VARCHAR(200) NOT NULL,
    host_full_name VARCHAR(250) NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    condition_value VARCHAR(20) NOT NULL,
    available_rooms INTEGER NOT NULL,
    fully_occupied BOOLEAN NOT NULL,
    refreshed_at TIMESTAMP NOT NULL
);

