DROP TABLE IF EXISTS activity_log;

CREATE TABLE activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accommodation_name VARCHAR(200) NOT NULL,
    event_time TIMESTAMP NOT NULL,
    event_type VARCHAR(100) NOT NULL
);
